import { Video, Category, Grade } from './types';

export const categories: Category[] = [
  { id: 'algebra', name: 'Algebra', icon: 'Calculator', count: 42 },
  { id: 'geometry', name: 'Geometry', icon: 'Shapes', count: 35 },
  { id: 'calculus', name: 'Calculus', icon: 'FunctionSquare', count: 28 },
  { id: 'statistics', name: 'Statistics', icon: 'BarChart3', count: 15 },
  { id: 'trigonometry', name: 'Trigonometry', icon: 'Ruler', count: 20 },
  { id: 'arithmetic', name: 'Arithmetic', icon: 'Sigma', count: 50 },
];

export const grades: Grade[] = [
  { id: 'prep1', name: 'Prep 1' },
  { id: 'prep2', name: 'Prep 2' },
  { id: 'prep3', name: 'Prep 3' },
  { id: 'sec1', name: 'Sec 1' },
  { id: 'sec2', name: 'Sec 2' },
  { id: 'sec3', name: 'Sec 3' },
];

export const mockVideos: Video[] = [
  {
    id: '1',
    title: 'أساسيات الجبر - حل المعادلات من الدرجة الأولى',
    description: 'في هذا الدرس سنتعلم الطرق الأساسية والمبسطة لحل المعادلات الخطية من الدرجة الأولى. الشرح يعتمد على خطوات واضحة ومباشرة لتجنب أي تشتيت للطلاب وتثبيت الفهم.',
    category: 'algebra',
    grade: 'prep1',
    youtubeId: 'j8e8s1I2n7Y',
    duration: '15:20',
    views: 1250,
    date: '2026-05-15',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'مقدمة في حساب المثلثات - الدوال الأساسية',
    description: 'شرح مبسط للدوال المثلثية الأساسية (الجا والجتا والظا). نركز في هذا الدرس على كيفية استنتاج القوانين بدون حفظ لضمان فهم عميق يريح الطالب.',
    category: 'trigonometry',
    grade: 'sec1',
    youtubeId: 'F2J3xEU5i1M',
    duration: '22:45',
    views: 840,
    date: '2026-05-10',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'نظريات الهندسة المستوية - المثلثات المتطابقة',
    description: 'تطبيق عملي على حالات تطابق المثلثات. هذا الدرس يساعد الطلاب على ربط الأشكال الهندسية وتخيلها بشكل منطقي.',
    category: 'geometry',
    grade: 'prep2',
    youtubeId: 'X4H0A2pA7-E',
    duration: '18:10',
    views: 2100,
    date: '2026-05-01',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'التفاضل: قواعد الاشتقاق الأساسية',
    description: 'مراجعة شاملة لجميع قواعد الاشتقاق التي ستحتاجها في منهج الثانوية العامة مع أمثلة وتطبيقات متدرجة الصعوبة.',
    category: 'calculus',
    grade: 'sec3',
    youtubeId: '5y1sP8Xk17Y',
    duration: '35:00',
    views: 3450,
    date: '2026-04-20',
  },
  {
    id: '5',
    title: 'مقاييس النزعة المركزية - الإحصاء الوصفي',
    description: 'الوسط والوسيط والمنوال بأمثلة عملية من الحياة اليومية لتبسيط الفهم وتحبيب الطالب في مادة الإحصاء.',
    category: 'statistics',
    grade: 'prep3',
    youtubeId: 'H58vB0QfD08',
    duration: '12:30',
    views: 960,
    date: '2026-04-18',
  },
  {
    id: '6',
    title: 'التكامل المحدود وتطبيقاته',
    description: 'شرح طريقة حساب المساحات تحت المنحنيات باستخدام التكامل المحدود، بأسلوب يعتمد على التفكير وليس فقط تطبيق القوانين.',
    category: 'calculus',
    grade: 'sec3',
    youtubeId: '3GZ_B7B1Zqk',
    duration: '40:15',
    views: 4200,
    date: '2026-04-15',
  },
  {
    id: '7',
    title: 'المتتاليات الحسابية والهندسية',
    description: 'كيف نفرق بين المتتالية الحسابية والهندسية؟ وكيف نستنتج الحد العام والمجموع؟ هذا ما سنشرحه خطوة بخطوة.',
    category: 'algebra',
    grade: 'sec2',
    youtubeId: '7Xz6X6Kx2Lg',
    duration: '28:50',
    views: 1100,
    date: '2026-04-10',
  }
];
